### ISSUE TITLE
reduce test concatenates element to start of array

### ISSUE THREAD

**Issue by ZooeyMiller** [foundersandcoders/mc-recursion#4]
in the reduce test: 

```js
  it('can be used to filter an array', () => {
    expect(reduce((a, b) => {
      if (a.length === 3) {
        return [a].concat(b)
      } else {
        return b
      }
    }, [], ["pumpkin", "pug", "po", "pof"]))
      .toEqual(['pug', 'pof']);
  });
```

the function passed to reduce concatenates filtered elements to the start of the array, rather than the end, which means (what I would consider to be) valid solutions won't pass this test. 

if it was changed to `return b.concat([a])` it would be fine.

**Comment by ZooeyMiller** [comment]
I used the supplied reduce solution, and it passes this test as is, which confuses me a little.

for reference, supplied solution: 
```js
const reduce = (f, acc, arr) => {
  if (arr.length <= 0) {
    return acc
  }
  return f(arr[0], reduce(f, acc, arr.slice(1)))
}
```

my solution: 
```js
const reduce = (f, acc, arr) => {
  if (arr.length === 0) {
    return acc;
  } else {
    return reduce(f, f(arr[0], acc), arr.slice(1));
  }
};
```

given this, it is of course just possible that my solution does not behave as is intended.

would be useful to get your input @Jwhiles

**Comment by Jwhiles** [comment]
@ZooeyMiller I think the confusion comes down to there being a number of different ways of defining reduce/fold - and possibly indicates that my instructions and test cases are not clear enough. 

Also I think I have asked people to define a reduce/fold function that behaves differently to how the default array method in JavaScript works. 

```
add = x, y => x + y

foldr :: (a -> b -> b) -> b -> [a] -> [b] // the function I expected people to write
foldr add 0 [1,2,3] ->
1 + foldr add 0 [2, 3]
1 + 2 + foldr add 0 [3]
1 + 2 + 3 foldr add 0 []
1 + 2 + 3 + 0

foldl :: (a -> b -> a) -> a -> [b] -> [a] // the way JavaScript's fold works
foldl add 0 [1,2,3] ->
foldl add (0 + 1) [2, 3]
foldl add (0 + 1 + 2) [3]
foldl add (0 + 1 + 2 + 3) []
```

[This really in depth article explains more about how these differnt folds work](https://wiki.haskell.org/Foldr_Foldl_Foldl%27) 

I'm open to changing this exercise/test case if you want to make a PR?

**Comment by ZooeyMiller** [comment]
happy to make a PR to change this.

I think mirroring `foldl`/reduce as it is in JS is probs most appropriate for this challenge, since right to left stuff doesn't tend to be where people's brains go to immediately.
